services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/exampledb
#      - SPRING_DATASOURCE_USERNAME=example
#      - SPRING_DATASOURCE_PASSWORD=password
#    volumes:
#      - .:/app
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: raquettelover
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
